"""empty message

Revision ID: 38e56ad1762b
Revises: 03cd8721f55d
Create Date: 2022-06-05 23:20:22.087249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e56ad1762b'
down_revision = '03cd8721f55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('uid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
